### ISSUE TITLE
Crash when CRL Download/Check is enabled

### ISSUE THREAD

**Issue by garz75** [certificate-helper/TLS-Inspector#96]
**Affected Version:**

1.7.0 (37) 

**Is this a Test Flight version or the App Store version?**

TestFlight

**Device and iOS Version:**

iPhone 7 iOS 11.2.6

**What steps will reproduce the problem?**

1. Enable CRL Check in the preferences
2. use TLS inspector on an SSL site with an untrusted certificate (e.g. https://untrusted-root.badssl.com or https://pki-demo.idnomic.net, either by entering the host name in the app or within Safari

**What is the expected output?**

TLS Inspector shows the certificate detail

**What do you see instead?**

TLS Inspector crashes early (the interface the is sometimes displayed for less than a second, then crashes) 

**Please provide any additional information below.**

disabling the CRL download option fixes the issue for the sites above.

**Comment by ecnepsnai** [comment]
Hi @garz75, thank you for the detailed bug report.

The issue is right here: https://github.com/certificate-helper/TLS-Inspector/blob/1.7.0_ocsp/CertificateKit/Revocation/CKCRLManager.m#L64

I forgot to first check if there are actually any CRL distribution points on the certificate before trying to download them. I'll make sure this is fixed in time for the next beta.

**Comment by ecnepsnai** [comment]
Merged. Also resolved a number of other potential bugs involving OCSP and CRL.

**Comment by igerzog** [comment]
Version 1.7.0 (38) - TestFlight - does not resolve the issue with CRL download and check. App still crashes after enabling this switch.

**Comment by ecnepsnai** [comment]
@igezog what is the FQDN of the site you're trying to inspect? I can no longer replicate the crash with untrusted-root.badssl.com

**Comment by ecnepsnai** [comment]
Thank you - I'll have this fixed for the next beta.

**Comment by ecnepsnai** [comment]
The fix for the crash has been merged and is included in the latest beta (3).
